export function installFacebook({getCloud,getUser,getView,toast}) {
 let popup=null;
 async function request(body){const user=getUser(),cloud=getCloud();if(!cloud||!user||user.id==='local')throw Error('Sign in to a cloud account first.');const {data,error}=await cloud.functions.invoke('facebook',{body});if(getUser()?.id!==user.id)throw Error('Your account changed.');if(error){let message='Facebook connection request failed.';try{message=(await error.context.json()).error||message;}catch{}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
 async function refresh(panel){try{const result=await request({action:'status'});if(!panel.isConnected)return;const select=panel.querySelector('select');select.replaceChildren(new Option('Select your Page',''));for(const page of result.pages)select.add(new Option(page.name,page.page_id));select.value=result.pageId||'';panel.querySelector('[data-status]').textContent=result.connected?'Connected: '+select.selectedOptions[0].textContent:result.pages.length?'Choose the Page to connect.':'Not connected';panel.querySelector('[data-disconnect]').disabled=!result.pages.length;}catch(e){if(panel.isConnected)panel.querySelector('[data-status]').textContent=e.message;}}
 function mount(){if(getView()!=='Channels'||document.querySelector('#facebook-channel'))return;const content=document.querySelector('#content');if(!content)return;const panel=document.createElement('section');panel.id='facebook-channel';panel.className='card';panel.innerHTML='<h2>Facebook Page</h2><p data-status>Checking connection…</p><label>Page<select aria-label="Facebook Page"><option value="">Select your Page</option></select></label><div class="row"><button data-connect>Connect Facebook Page</button><button class="secondary" data-disconnect disabled>Disconnect Facebook</button></div><p class="muted">Publish text, JPG/PNG images or MP4 videos up to 12 MB from the Facebook preview. Blog posts can also be sent to your Page.</p>';content.append(panel);
 panel.querySelector('[data-connect]').onclick=async()=>{popup=window.open('about:blank','creativerelay-facebook','width=650,height=760');if(!popup)return toast('Allow popups, then connect again.');try{const result=await request({action:'connect'}),url=new URL(result.url);if(url.origin!=='https://www.facebook.com')throw Error('Unexpected connection URL.');popup.location.href=url.href;}catch(e){popup?.close();toast(e.message);}};
 panel.querySelector('select').onchange=async e=>{if(!e.target.value)return;try{await request({action:'select',pageId:e.target.value});await refresh(panel);}catch(error){toast(error.message);await refresh(panel);}};
 panel.querySelector('[data-disconnect]').onclick=async()=>{try{await request({action:'disconnect'});await refresh(panel);}catch(e){toast(e.message);}};
 void refresh(panel);
 }
 window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==popup||e.data?.type!=='creativerelay-facebook')return;popup?.close();popup=null;toast(e.data.result==='connected'?'Facebook authorized. Select your Page in Channels.':'Facebook connection: '+e.data.result);const panel=document.querySelector('#facebook-channel');if(panel)void refresh(panel);});
 const url=new URL(location.href),result=url.searchParams.get('facebook');if(result){url.searchParams.delete('facebook');history.replaceState(null,'',url.href);if(window.opener){window.opener.postMessage({type:'creativerelay-facebook',result},location.origin);window.close();}else setTimeout(()=>toast(result==='connected'?'Facebook authorized. Select your Page in Channels.':'Facebook connection: '+result),800);}
 new MutationObserver(mount).observe(document.querySelector('#app'),{childList:true,subtree:true});mount();
}
